name: binary_data
description: "Bitwise operations and binary data manipulation utilities."
version: 0.0.1
homepage:

# publish_to: 'none'

environment:
  sdk: ^3.4.0
  # flutter: ">=1.17.0"

dependencies:
  # flutter:
  #   sdk: flutter
  collection: ^1.18.0 
  meta: ^1.11.0
  # recase: ^4.1.0 

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter_lints: ^4.0.0

 