name: cmdr
description: "Commander/Host side utilities for interfacing with embedded devices + other general utilities."
version: 0.0.1
# homepage:

publish_to: "none"

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  type_ext: ^0.0.1
  binary_data: ^0.0.1

  flutter:
    sdk: flutter
  async: ^2.11.0
  meta: ^1.11.0
  collection: ^1.18.0
  quiver: ^3.2.2

  csv: ^6.0.0
  file_picker: ^8.0.3
  fl_chart: ^0.69.2
  intel_hex: ^1.2.1
  libserialport: ^0.3.0+1
  recase: ^4.1.0
  shared_preferences: ^2.2.3
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # melos: ^6.2.0
  lints: ^4.0.0
  test: ^1.25.5
