name: cmdr_common
description: "Common utilities for components of the cmdr package."
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: ^3.4.0 

dependencies: 
  flutter:
    sdk: flutter
  collection: ^1.18.0 
  meta: ^1.11.0 

dev_dependencies: 
  lints: ^4.0.0
  flutter_lints: ^4.0.0